In [ ]:
import requests
import pandas as pd

# Open-Meteo API URL for Mathura
url = (
    "https://api.open-meteo.com/v1/forecast"
    "?latitude=27.49"
    "&longitude=77.67"
    "&current=temperature_2m,relative_humidity_2m,wind_speed_10m"
)

# Send request to API
response = requests.get(url)

# Check status
print("Status Code:", response.status_code)

# Convert JSON response to Python dictionary
data = response.json()

# See complete JSON
print(data)

# Extract only current weather
current_weather = data["current"]

# Convert to DataFrame
df = pd.DataFrame([current_weather])

df

Status Code: 200
{'latitude': 27.521967, 'longitude': 77.70437, 'generationtime_ms': 0.6059408187866211, 'utc_offset_seconds': 0, 'timezone': 'GMT', 'timezone_abbreviation': 'GMT', 'elevation': 180.0, 'current_units': {'time': 'iso8601', 'interval': 'seconds', 'temperature_2m': '°C', 'relative_humidity_2m': '%', 'wind_speed_10m': 'km/h'}, 'current': {'time': '2026-10-12T16:30', 'interval': 900, 'temperature_2m': 25.5, 'relative_humidity_2m': 74, 'wind_speed_10m': 4.4}}

,time,interval,temperature_2m,relative_humidity_2m,wind_speed_10m
0,2026-10-12T16:30,900,25.5,74,4.4

In [ ]:
import requests
import pandas as pd

url = (
    "https://api.open-meteo.com/v1/forecast"
    "?latitude=27.49"
    "&longitude=77.67"
    "&hourly=temperature_2m,relative_humidity_2m,wind_speed_10m"
)

response = requests.get(url)
data = response.json()

hourly = data["hourly"]

df = pd.DataFrame(hourly)

df

                 time  temperature_2m  relative_humidity_2m  wind_speed_10m
0    2026-10-12T00:00            22.2                    83             8.1
1    2026-10-12T01:00            22.1                    84            16.2
2    2026-10-12T02:00            22.1                    89            14.1
3    2026-10-12T03:00            22.3                    93             8.9
4    2026-10-12T04:00            23.9                    83             8.2
..                ...             ...                   ...             ...
163  2026-10-18T19:00            20.8                    84             4.1
164  2026-10-18T20:00            19.9                    89             3.6
165  2026-10-18T21:00            19.0                    92             3.3
166  2026-10-18T22:00            18.4                    94             3.2
167  2026-10-18T23:00            18.2                    94             3.3

[168 rows x 4 columns]

In [ ]:
import requests
import pandas as pd

url = (
    "https://api.open-meteo.com/v1/forecast"
    "?latitude=27.49"
    "&longitude=77.67"
    "&hourly=temperature_2m,relative_humidity_2m,wind_speed_10m"
    "&start_date=2026-10-12"
    "&end_date=2026-10-12"
)

response = requests.get(url)

data = response.json()

hourly_data = data["hourly"]

df = pd.DataFrame(hourly_data)

df

                time  temperature_2m  relative_humidity_2m  wind_speed_10m
0   2026-10-12T00:00            22.2                    83             8.1
1   2026-10-12T01:00            22.1                    84            16.2
2   2026-10-12T02:00            22.1                    89            14.1
3   2026-10-12T03:00            22.3                    93             8.9
4   2026-10-12T04:00            23.9                    83             8.2
5   2026-10-12T05:00            26.3                    67             8.8
6   2026-10-12T06:00            28.3                    62             8.5
7   2026-10-12T07:00            30.2                    52             4.6
8   2026-10-12T08:00            31.4                    45             5.4
9   2026-10-12T09:00            31.7                    44             6.0
10  2026-10-12T10:00            31.5                    44             6.5
11  2026-10-12T11:00            30.9                    46             6.6
12  2026-10-12T12:00            29.3                    54             9.5
13  2026-10-12T13:00            27.8                    58             8.7
14  2026-10-12T14:00            27.1                    62             8.0
15  2026-10-12T15:00            26.5                    66             7.1
16  2026-10-12T16:00            25.8                    72             4.8
17  2026-10-12T17:00            25.2                    76             4.3
18  2026-10-12T18:00            24.6                    79             4.1
19  2026-10-12T19:00            24.2                    82             3.6
20  2026-10-12T20:00            23.9                    83             3.6
21  2026-10-12T21:00            23.5                    85             3.6
22  2026-10-12T22:00            23.2                    87             3.4
23  2026-10-12T23:00            23.0                    88             2.9

In [ ]:
import requests
import pandas as pd

url = (
    "https://api.open-meteo.com/v1/forecast"
    "?latitude=27.49"
    "&longitude=77.67"
    "&hourly=temperature_2m,relative_humidity_2m,wind_speed_10m"
    "&start_date=2026-10-12"
    "&end_date=2026-10-13"
)

response = requests.get(url)

data = response.json()

hourly_data = data["hourly"]

df = pd.DataFrame(hourly_data)

df

                time  temperature_2m  relative_humidity_2m  wind_speed_10m
0   2026-10-12T00:00            22.2                    83             8.1
1   2026-10-12T01:00            22.1                    84            16.2
2   2026-10-12T02:00            22.1                    89            14.1
3   2026-10-12T03:00            22.3                    93             8.9
4   2026-10-12T04:00            23.9                    83             8.2
5   2026-10-12T05:00            26.3                    67             8.8
6   2026-10-12T06:00            28.3                    62             8.5
7   2026-10-12T07:00            30.2                    52             4.6
8   2026-10-12T08:00            31.4                    45             5.4
9   2026-10-12T09:00            31.7                    44             6.0
10  2026-10-12T10:00            31.5                    44             6.5
11  2026-10-12T11:00            30.9                    46             6.6
12  2026-10-12T12:00            29.3                    54             9.5
13  2026-10-12T13:00            27.8                    58             8.7
14  2026-10-12T14:00            27.1                    62             8.0
15  2026-10-12T15:00            26.5                    66             7.1
16  2026-10-12T16:00            25.8                    72             4.8
17  2026-10-12T17:00            25.2                    76             4.3
18  2026-10-12T18:00            24.6                    79             4.1
19  2026-10-12T19:00            24.2                    82             3.6
20  2026-10-12T20:00            23.9                    83             3.6
21  2026-10-12T21:00            23.5                    85             3.6
22  2026-10-12T22:00            23.2                    87             3.4
23  2026-10-12T23:00            23.0                    88             2.9
24  2026-10-13T00:00            22.8                    89             2.4
25  2026-10-13T01:00            22.7                    90             1.9
26  2026-10-13T02:00            24.1                    83             2.7
27  2026-10-13T03:00            26.5                    70             2.3
28  2026-10-13T04:00            28.5                    60             2.4
29  2026-10-13T05:00            30.0                    53             2.0
30  2026-10-13T06:00            31.1                    48             1.0
31  2026-10-13T07:00            31.7                    46             2.4
32  2026-10-13T08:00            32.2                    44             3.0
33  2026-10-13T09:00            32.2                    43             3.8
34  2026-10-13T10:00            32.0                    44             4.5
35  2026-10-13T11:00            31.5                    46             4.7
36  2026-10-13T12:00            29.9                    55             3.7
37  2026-10-13T13:00            28.2                    60             5.4
38  2026-10-13T14:00            27.5                    64             5.5
39  2026-10-13T15:00            26.9                    67             8.3
40  2026-10-13T16:00            26.3                    69             8.2
41  2026-10-13T17:00            25.7                    71             6.2
42  2026-10-13T18:00            25.1                    74             5.7
43  2026-10-13T19:00            24.7                    75             5.4
44  2026-10-13T20:00            24.4                    77             5.6
45  2026-10-13T21:00            23.8                    80             4.8
46  2026-10-13T22:00            23.5                    81             4.8
47  2026-10-13T23:00            23.2                    83             3.9

In [7]:
import requests
import pandas as pd

# API endpoint
url = "https://www.weatherunion.com/gw/weather/external/v0/get_locality_weather_data"

# Locality parameter
params = {
    "locality_id": "ZWL005971"
}

# Request headers
headers = {
    "content-type": "application/json",
    "x-zomato-api-key": "0c171bc7ac6c80fffee513762736092e"
}

# Send GET request
response = requests.get(url, params=params, headers=headers)

# Check HTTP status
print("Status Code:", response.status_code)

# Convert JSON response to Python dictionary
data = response.json()

print(data)

# Extract weather data
weather = data["locality_weather_data"]

# Convert to DataFrame
df = pd.DataFrame([weather])

df

Status Code: 200
{'status': '200', 'message': '', 'device_type': 1, 'locality_weather_data': {'temperature': 33.03, 'humidity': 59.28, 'wind_speed': 9.86, 'wind_direction': 89.6, 'rain_intensity': 0, 'rain_accumulation': 0, 'aqi_pm_10': None, 'aqi_pm_2_point_5': None}}

,temperature,humidity,wind_speed,wind_direction,rain_intensity,rain_accumulation,aqi_pm_10,aqi_pm_2_point_5
0,33.03,59.28,9.86,89.6,0,0,None,None