<a href="https://colab.research.google.com/github/Shubham-chaudhary07/Colab_work_ML/blob/main/DataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from pandas import Series, DataFrame
import pandas as pd

In [11]:
#Now we'll learn DataFrames

#Let's get some data to play with. How about the NFL?
import webbrowser
website = 'http://en.wikipedia.org/wiki/NFL_win-loss_records'
webbrowser.open(website)

False

In [35]:
dict={
    'name': ['shubham', 'adarshan', 'shubham', 'shubham'],
    'age':[21,22,25,35],
    'mobile':[99999999,9999999,999999,99999999],
    'marks':[99,98,97,96]
}

In [36]:
df=DataFrame(dict)

In [37]:
print(df.head())

print(df.tail())

       name  age    mobile  marks
0   shubham   21  99999999     99
1  adarshan   22   9999999     98
2   shubham   25    999999     97
3   shubham   35  99999999     96
       name  age    mobile  marks
0   shubham   21  99999999     99
1  adarshan   22   9999999     98
2   shubham   25    999999     97
3   shubham   35  99999999     96

In [38]:
df1=pd.read_csv("/content/new_data - Sheet1.csv")

In [39]:
df1.head()

      name  age section   mobile
0  shubham   19      AX  9999999
1     aman   45      AD   999999
2      dev   25      AF   999999
3  tejveer   32      AG   999999

In [40]:
df1.isnull().sum()

name       0
age        0
section    0
mobile     0
dtype: int64

In [48]:
means=df1['age'].mean()
print(means)

30.25

In [52]:
df1['age']=(means)

In [53]:
df1

      name    age section   mobile
0  shubham  30.25      AX  9999999
1     aman  30.25      AD   999999
2      dev  30.25      AF   999999
3  tejveer  30.25      AG   999999